apiVersion: v1
kind: Pod
metadata:
  name: user-pod
spec:
  containers:
    - name: user-secret
      image: nginx:1.7.9
      env:
        - name: SECRET_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: user
        - name: SECRET_PWD
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: pwd