apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pod1
  name: pod1
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: httpd:2.4.41-alpine
        name: pod1-containers
