apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: test-container
      image: kubegoldenguide/alpine-spin:1.0.0
      envFrom:
      - configMapRef:
          name: app-config
  restartPolicy: Never