apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: server
    image: python:2.7-alpine
    livenessProbe:
      exec:
        command:
          - ls
          - index.html
      initialDelaySeconds: 60
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 30
      failureThreshold: 4
    env:
      - name: DELAY_ST
        value: "45"
    command: ["/bin/sh"]
    args:
      - -c
      - echo 'sleeping...'; sleep $(DELAY_ST); echo 'starte' ; python -m SimpleHTTPServer