apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: server
    image: nginx:1.7.9
    readinessProbe:
      exec:
        command:
          - cat
          - /tmp/ready
      initialDelaySeconds: 5
      failureThreshold: 10
      periodSeconds: 10
