apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
    - name: user-secret
      image: mysql:5.7
      env:
        - name: SECRET_USERNAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: user
        - name: SECRET_PWD
          valueFrom:
            secretKeyRef:
              name: secret-config
              key: pwd