kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-persistent-storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/mysql"
    server: nfs01