kind: PersistentVolume
apiVersion: v1
metadata:
  name: wordpress-persistent-storage
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/html"
    server: nfs01
  volumeName: wordpress-persistent-storage
