kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wordpress-persistent-storage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi