apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: vote
spec:
  type: NodePort
  selector:
    app: result
  ports:
    - protocol: TCP
      nodePort: 31001
      port: 5001
      targetPort: 80