apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote
spec:
  selector:
    matchLabels:
      app: result
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: rescrr
        image: dockersamples/examplevotingapp_result:before
        ports:
        - containerPort: 80