apiVersion: v1
kind: Service
metadata:
  name: moodys-service
spec:
  type: NodePort
  selector:
    app: crr-labels
  ports:
    - protocol: TCP
      nodePort: 31080
      port: 5000
      targetPort: 80