apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: vote
spec:
  type: NodePort
  selector:
    app: voting
  ports:
    - protocol: TCP
      nodePort: 31000
      port: 5000
      targetPort: 80