apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: work
  name: work
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work
  template:
    metadata:
      labels:
        app: work
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: worker
